# Generated by Django 5.2.8 on 2025-11-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('listing_date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('sellerID', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
